Add verification step before upload

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -55,7 +55,12 @@ jobs:
 
       - run: npm ci
       - run: npm run build
-      - run: ls -R
+
+      - run: |
+        if [ ! -d ".next" ] || [ -z "$(ls -A .next)" ]; then
+          echo ".next directory is missing or empty";
+          exit 1;
+        fi
 
       - name: Upload build artifact
         uses: actions/upload-artifact@v4
