Fix verification step

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -57,10 +57,10 @@ jobs:
       - run: npm run build
 
       - run: |
-        if [ ! -d ".next" ] || [ -z "$(ls -A .next)" ]; then
-          echo ".next directory is missing or empty";
-          exit 1;
-        fi
+          if [ ! -d ".next" ] || [ -z "$(ls -A .next)" ]; then
+            echo ".next directory is missing or empty";
+            exit 1;
+          fi
 
       - name: Upload build artifact
         uses: actions/upload-artifact@v4
